package com.divs.model;
// Generated May 15, 2023, 12:56:10 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Insurancepolicy generated by hbm2java
 */
@Entity
@Table(name = "insurancepolicy", catalog = "divs")
public class Insurancepolicy implements java.io.Serializable {


	private static final long serialVersionUID = 1L;
	private Integer pid;
	private String pname;
	private Integer ptenure;
	private String ptype;

	public Insurancepolicy() {
	}

	public Insurancepolicy(String pname, Integer ptenure, String ptype) {
		this.pname = pname;
		this.ptenure = ptenure;
		this.ptype = ptype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "pname")
	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Column(name = "ptenure")
	public Integer getPtenure() {
		return this.ptenure;
	}

	public void setPtenure(Integer ptenure) {
		this.ptenure = ptenure;
	}

	@Column(name = "ptype")
	public String getPtype() {
		return this.ptype;
	}

	public void setPtype(String ptype) {
		this.ptype = ptype;
	}

	@Override
	public String toString() {
		return "Insurancepolicy [pid=" + pid + ", pname=" + pname + ", ptenure=" + ptenure + ", ptype=" + ptype + "]";
	}
	

}
